version: "3"
services:
  distort:
    container_name: distort-server
    restart: always
    image: ryco117/distort-server:latest
    build: .
    command: npm start
    ports:
      - "6945:6945"
    depends_on:
      - mongo
      - ipfs
  mongo:
    container_name: mongo
    image: mongo
    restart: always
    logging:
      driver: "none"
  ipfs:
    container_name: ipfs
    image: ipfs/go-ipfs:latest
    command: daemon --enable-pubsub-experiment
    restart: always
    ports:
      - "4001:4001"
      - "127.0.0.1:5001:5001"
      - "127.0.0.1:8080:8080"
