version: "3"
services:
  app:
    stdin_open: true
    tty: true
    container_name: distort_server
    restart: always
    build: .
    command: npm start
    volumes:
      - .:/usr/app/
      - /usr/app/node_modules
    ports:
      - "6945:6945"
    depends_on:
      - mongo
      - ipfs
  mongo:
    container_name: mongo
    image: mongo
    restart: always
    logging:
      driver: "none"
  ipfs:
    container_name: ipfs
    image: ipfs/go-ipfs:latest
    command: --enable-pubsub-experiment
    restart: always
    ports:
      - "4001:4001"
      - "5001:5001"
      - "8080:8080"
